Repository pycalphad/pycalphad, pull requests merged in 2024-07, with the labels that each got.

#536 ENH/BLD: Drop dedicated macOS universal wheel builds
  .github/workflows/deploy.yaml
Labels: enhancement

#538 FIX/MAINT: np.infty -> np.inf (numpy 2.0 compat)
  pycalphad/plot/binary/compsets.py
  pycalphad/plot/triangular.py
  pycalphad/tests/databases/Al-Mg_Zhong.tdb
  pycalphad/tests/test_plot.py
Labels: bug

#543 Mapping
  docs/AlNi.png
  docs/examples/Mapping.nblink
  docs/examples/index.rst
  examples/BinaryExamples.ipynb
  examples/ChargedPhases.ipynb
  examples/CrFeNb_Jacob2016.tdb
  examples/MappingExamples.ipynb
  examples/TernaryExamples.ipynb
  pycalphad/__init__.py
  pycalphad/mapping/__init__.py
  pycalphad/mapping/compat_api.py
  pycalphad/mapping/plotting.py
  pycalphad/mapping/primitives.py
  pycalphad/mapping/starting_points.py
  pycalphad/mapping/strategy/__init__.py
  pycalphad/mapping/strategy/binary_strategy.py
  pycalphad/mapping/strategy/isopleth_strategy.py
  pycalphad/mapping/strategy/step_strategy.py
  pycalphad/mapping/strategy/strategy_base.py
  pycalphad/mapping/strategy/strategy_utils.py
  pycalphad/mapping/strategy/ternary_strategy.py
  pycalphad/mapping/utils.py
  pycalphad/mapping/zpf_checks.py
  pycalphad/mapping/zpf_equilibrium.py
  pycalphad/tests/databases/CrFeNb_Jacob2016.tdb
  pycalphad/tests/test_mapping_strategy.py
  pycalphad/tests/test_mapping_zpf_checks.py
  setup.py
Labels: mapping
